#!/bin/bash

source .env
export DEBUG="*:*"
TESTID=$1

/bin/bash ./prepareTestEnv $TESTID

_DIR="./test.$TESTID"
_FILE="$_DIR/data.json"
_LOG=`realpath $_DIR/log`
FNAME=`realpath $_FILE`

CREDID=`cat $_DIR/credential_registration.json | jq -r '.id'`
if [ "x$CREDID" = "x" ]
then
    echo "Could not determine credential ID"
    exit
else
    echo "Credential ID: $CREDID"
fi

DID=`cat $_DIR/identifier_registration.json | jq -r '.did'`
if [ "x$DID" = "x" ]
then
    echo "Could not determine identifier ID"
    exit
else
    echo "Identifier ID: $DID"
fi

ISSID=`cat $_DIR/issuer_registration.json | jq -r '.id'`
if [ "x$ISSID" = "x" ]
then
    echo "Could not determine issuer ID"
    exit
else
    echo "issuer ID: $ISSID"
fi

echo "Removing issuer"
yarn --cwd $YARNDIR do delete:issuer -u $MANAGER_API -s $MANAGER_TOKEN -i $ISSID 2>> $_LOG
echo "Removing identifier"
yarn --cwd $YARNDIR do delete:identifier -u $MANAGER_API -s $MANAGER_TOKEN -i $DID 2>> $_LOG
echo "Removing credential"
yarn --cwd $YARNDIR do delete:credential -u $MANAGER_API -s $MANAGER_TOKEN -i $CREDID 2>> $_LOG


