#!/bin/bash

source .env
export DEBUG="*:*"
TESTID=$1

/bin/bash ./prepareTestEnv $TESTID

_DIR="./test.$TESTID"
_FILE="$_DIR/data.json"
_LOG=`realpath $_DIR/log`
FNAME=`realpath $_FILE`

echo "Creating jwt_vc_json credential configuration"
echo "{
  \"format\": \"jwt_vc_json\",
  \"cryptographic_binding_methods_supported\":[\"did:jwk\",\"did:key\"],
  \"cryptographic_suites_supported\":[\"ES256\",\"EdDSA\"],
  \"proof_types_supported\":{
    \"jwt\":{
      \"proof_signing_alg_values_supported\":[\"ES256\",\"EdDSA\"]
    }
  },
  \"scope\":\"$CREDENTIAL_NAME\",
  \"display\":[{
    \"name\":\"Test Credential\",
    \"description\":\"API Testing Credential\"
  }],
  \"credential_definition\":{
    \"type\":[\"VerifiableCredential\",\"$CREDENTIAL_NAME\"],
    \"credentialSubject\":{
      \"name\":{
        \"value_type\":\"string\",
        \"mandatory\":true,
        \"display\":[{
          \"name\":\"Full name\"
        }]
      }
    }
  }  
}" > $_FILE

yarn --cwd $YARNDIR do quote -d $FNAME > $_DIR/credential_configuration.json 2>> $_LOG
CREDCONF=`cat $_DIR/credential_configuration.json | jq '.content'`

echo "Creating credential on remote"
echo "{
  \"name\": \"$CREDENTIAL_NAME\",
  \"configuration\": $CREDCONF
}" > $_FILE

yarn --cwd $YARNDIR do register:credential -u $MANAGER_API -s $MANAGER_TOKEN -d $FNAME > $_DIR/credential_registration.json 2>> $_LOG
CREDID=`cat $_DIR/credential_registration.json | jq -r '.id'`
if [ "x$CREDID" = "x" ]
then
    echo "Could not determine credential ID"
    exit
else
    echo "Credential ID: $CREDID"
fi

echo "Creating identifier on remote"
echo "{
  \"did\": \"does not matter\",
  \"provider\": \"did:jwk\",
  \"alias\": \"$IDENTIFIER_ALIAS\",
  \"keytype\": \"Secp256r1\"
}" > $_FILE

yarn --cwd $YARNDIR do register:identifier -u $MANAGER_API -s $MANAGER_TOKEN -d $FNAME > $_DIR/identifier_registration.json 2>> $_LOG
DID=`cat $_DIR/identifier_registration.json | jq -r '.did'`
if [ "x$DID" = "x" ]
then
    echo "Could not determine identifier ID"
    exit
else
    echo "Identifier ID: $DID"
fi

echo "{
  \"name\": \"$ISSUER_NAME\",
  \"did\": \"$IDENTIFIER_ALIAS\",
  \"baseUrl\": \"$MANAGER_API/$ISSUER_NAME\",
  \"adminToken\": \"$ISSUER_TOKEN\",
  \"metadata\": {
    \"display\": [{
      \"name\": \"GenericIssuer\",
      \"description\": \"GenericIssuer\",
      \"logo\": {
        \"uri\": \"https://example.com/logo.png\",
        \"alt_text\": \"Alt text\"
      }
    }],
    \"credential_configurations_supported\": {
      \"$CREDENTIAL_NAME\": {},
      \"${CREDENTIAL_NAME}_SD\": {
          \"format\": \"dc+sd-jwt\",
          \"extends\": \"$CREDENTIAL_NAME\"
      }
    }
  }
}" > $_FILE

yarn --cwd $YARNDIR do register:issuer -u $MANAGER_API -s $MANAGER_TOKEN -d $FNAME > $_DIR/issuer_registration.json 2>> $_LOG
ISSID=`cat $_DIR/issuer_registration.json | jq -r '.id'`
if [ "x$ISSID" = "x" ]
then
    echo "Could not determine issuer ID"
    exit
else
    echo "issuer ID: $ISSID"
fi

echo "Restarting remote agent"
yarn --cwd $YARNDIR do restart -u $MANAGER_API -s $MANAGER_TOKEN 2>> $_LOG
sleep 3

yarn --cwd $YARNDIR do version -u $MANAGER_API > $_DIR/version.json 2>> $_LOG
VERSION=`cat $_DIR/version.json | jq -r '.version'`
while [ "x$VERSION" = "x" -o "x$VERSION" = "xnull" ]
do
    echo "Waiting a tad longer for the remote"
    sleep 3
    yarn --cwd $YARNDIR do version -u $MANAGER_API > $_DIR/version.json 2>> $_LOG
    VERSION=`cat $_DIR/version.json | jq -r '.version'`
done
echo "Version is $VERSION"

echo "Retrieving metadata of live issuer"
yarn --cwd $YARNDIR do get:json -u "$MANAGER_API/$ISSUER_NAME/.well-known/openid-credential-issuer" > $_DIR/openid-credential-issuer.json 2>>$_LOG
CREDISSUER=`cat $_DIR/openid-credential-issuer.json | jq -r '.credential_issuer'`
while [ ! "x$CREDISSUER" = "x$MANAGER_API/$ISSUER_NAME" ]
do
    sleep 3
    yarn --cwd $YARNDIR do get:json -u "$MANAGER_API/$ISSUER_NAME/.well-known/openid-credential-issuer" > $_DIR/openid-credential-issuer.json 2>>$_LOG
    CREDISSUER=`cat $_DIR/openid-credential-issuer.json | jq -r '.credential_issuer'`
done
echo "Credential issuer live at $CREDISSUER"

echo "End of issuer setup"
