#!/bin/bash

source .env
_FILE=issuer.data.json.$$

export DEBUG="*:*"

echo '{
  "name": "testcredential",
  "configuration": "{\"format\":\"jwt_vc_json\",\"cryptographic_binding_methods_supported\":[\"did:jwk\",\"did:key\"],\"cryptographic_suites_supported\":[\"ES256\",\"EdDSA\"],\"proof_types_supported\":{\"jwt\":{\"proof_signing_alg_values_supported\":[\"ES256\",\"EdDSA\"]}},\"scope\":\"TestCredential\",\"display\":[{\"name\":\"Test Credential\",\"description\":\"API Testing Credential\"}],\"credential_definition\":{\"type\":[\"VerifiableCredential\",\"TestCredential\"],\"credentialSubject\":{\"name\":{\"value_type\":\"string\",\"mandatory\":true,\"display\":[{\"name\":\"Full name\"}]}}}}"
}' > $_FILE
FNAME=`realpath ./$_FILE`

yarn --cwd .. do register:credential -u $MANAGER_API -s $MANAGER_TOKEN -d $FNAME 2>> .log

#rm $_FILE
