#!/bin/bash

source .env
_FILE=test.data.json.$$
    
echo '{
  "name": "test",
  "did": "secp256r1",
  "baseUrl": "https://agent.dev.eduwallet.nl/test",
  "adminToken": "TG6ZOFzqsY5QbRES76YamsK9wBxvqBbm",
  "metadata": {
    "display": [{
      "name": "GenericIssuer",
      "description": "GenericIssuer",
      "logo": {
        "uri": "https://example.com/logo.png",
        "alt_text": "Alt text"
      }
    }],
    "credential_configurations_supported": {
      "GenericCredential": {
        "format": "jwt_vc_json",
        "extends": "GenericCredential_JWT"
      }
    }
  }
}' > $_FILE
FNAME=`realpath $_FILE`

yarn --cwd .. do register:issuer -u $MANAGER_API -s $MANAGER_TOKEN -d $FNAME

rm $_FILE
