#!/bin/bash

TESTID=$1
URL=$2
TENANT=$3
SECRET=$4
CREDS=$5

DIR="./test.$TESTID"

echo "Checking OID4VCI metadata configuration for $TENANT"
# check the issuer well-known files
curl -s https://$URL/$TENANT/.well-known/openid-credential-issuer > $DIR/openid-credential-issuer.$TENANT.1.json
curl -s https://$URL/.well-known/openid-credential-issuer/$TENANT > $DIR/openid-credential-issuer.$TENANT.2.json
diff -q $DIR/openid-credential-issuer.$TENANT.1.json $DIR/openid-credential-issuer.$TENANT.2.json >/dev/null 2>&1
if [ "x$?" = "x1" ]
then
    echo "ERROR: $TENANT openid-credential-issuer data mismatch"
    exit 1
fi

ISSUERURL=`cat $DIR/openid-credential-issuer.$TENANT.1.json | jq -r '.credential_issuer'`
CREDENTIALENDPOINT=`cat $DIR/openid-credential-issuer.$TENANT.1.json | jq -r '.credential_endpoint'`
NONCEENDPOINT=`cat $DIR/openid-credential-issuer.$TENANT.1.json | jq -r '.nonce_endpoint'`

if [ ! "x$ISSUERURL" = "xhttps://$URL/$TENANT" ]
then
    echo "ERROR: $TENANT Issuer url from OpenID4VCI configuration ('$ISSUERURL') does not match expected url https://$URL/$TENANT"
    exit 1
fi

if [ "x$CREDENTIALENDPOINT" = "x" ]
then
    echo "ERROR: $TENANT OpenID4VCI configuration does not publish a credential_endpoint"
    exit 1
fi

if [ "x$NONCEENDPOINT" = "x" ]
then
    echo "ERROR: $TENANT OpenID4VCI configuration does not publish a nonce endpoint"
    exit 1
fi

echo "Checking openid configuration for $TENANT"
curl -s https://$URL/$TENANT/.well-known/openid-configuration > $DIR/openid-configuration.$TENANT.1.json
curl -s https://$URL/.well-known/openid-configuration/$TENANT > $DIR/openid-configuration.$TENANT.2.json
diff -q $DIR/openid-credential-issuer.$TENANT.1.json $DIR/openid-credential-issuer.$TENANT.2.json >/dev/null 2>&1
if [ "x$?" = "x1" ]
then
    echo "ERROR: $TENANT openid-configuration data mismatch"
    exit 1
fi

echo "Checking OAuth2 configuration for $TENANT"
curl -s https://$URL/$TENANT/.well-known/oauth-authorization-server > $DIR/oauth-authorization-server.$TENANT.1.json
curl -s https://$URL/.well-known/oauth-authorization-server/$TENANT > $DIR/oauth-authorization-server.$TENANT.2.json
diff -q $DIR/openid-credential-issuer.$TENANT.1.json $DIR/openid-credential-issuer.$TENANT.2.json >/dev/null 2>&1
if [ "x$?" = "x1" ]
then
    echo "ERROR: $TENANT oauth-authorization-server data mismatch"
    exit 1
fi

ISSUERURL=`cat $DIR/oauth-authorization-server.$TENANT.1.json | jq -r '.issuer'`
TOKENENDPOINT=`cat $DIR/oauth-authorization-server.$TENANT.1.json | jq -r '.token_endpoint'`

if [ ! "x$ISSUERURL" = "xhttps://$URL/$TENANT" ]
then
    echo "ERROR: $TENANT Issuer url from OAuth configuration ('$ISSUERURL') does not match expected url https://$URL/$TENANT"
    exit 1
fi

if [ "x$TOKENENDPOINT" = "x" ]
then
    echo "ERROR: $TENANT OAuth configuration does not publish a token endpoint"
    exit 1
fi

IFS=',' read -ra credentials <<< "$CREDS"
for CRED in ${credentials[@]}
do
    echo "Testing credential $CRED"

    /bin/bash ./get_credential $TENANT $CRED $DIR $SECRET
    if [ "x$?" = "x1" ]
    then
        exit 1
    fi

    /bin/bash ./check_credential $TENANT $CRED $DIR $URL
    if [ "x$?" = "x1" ]
    then
        exit 1
    fi
done
