#!/bin/bash

TENANT=$1
CRED=$2
DIR=$3
BASEURL=$4

HASFULLCRED=0
DATA=`cat credentials/${CRED}.json | jq -r '.data'`
if [ "x$DATA" = "x" -o "x$DATA" = "xnull" ]
then
    CREDDATA=`cat credentials/${CRED}.json | jq -r '.credential'`

    if [ "x$CREDDATA" = "x" -o "x$CREDDATA" = "xnull" ]
    then
        echo "ERROR: Input credential does not have data or credential information"
        exit 1
    fi
    HASFULLCRED=1
fi

CREDID=`cat credentials/${CRED}.json | jq -r '.credential_id'`
CTYPE=`cat credentials/${CRED}.json | jq -r '.type'`
CREDENTIAL=`cat $DIR/${TENANT}_${CRED}_credential.json | jq -r '.credentials[0].credential'`

if [ "$HASFULLCRED" = "0" ]
then
    KEYS= `cat credentials/${CRED}.json | jq -r '.data | keys | join(",")'`
else
    KEYS=""
    if [ "x$CTYPE" = "xvc2" ]
    then
        KEYS=`cat credentials/${CRED}.json | jq -r '.credential.credentialSubject | keys | join(",")'`
    fi
fi


if [ "x$CTYPE" = "xvc1" -o "x$CTYPE" = "xvc2" ]
then
    echo "Unpacking VCDM1.1 or VCDM2.0 credential"
    echo $CREDENTIAL > $DIR/${TENANT}_${CRED}_credential.jwt
    FILE=`realpath $DIR/${TENANT}_${CRED}_credential.jwt`
    yarn --cwd ../.. do jwt:expand -d $FILE > $DIR/${TENANT}_${CRED}_credential_unpacked.json
else
    echo "ERROR: $TENANT - $CRED Credential type $CTYPE not supported in check_credential"
    exit 1
fi

if [ "x$CTYPE" = "xvc2" ]
then
    echo "Checking VCDM2 header"
    # VCDM2: there may not be a claim named vc or vp
    VC=`cat $DIR/${TENANT}_${CRED}_credential_unpacked.json | jq '.payload.vc'`
    if [ ! "x$VC" = "xnull" ]
    then
        echo "ERROR: $TENANT - $CRED VCDM2 credential contains a vc claim"
        exit 1
    fi

    VP=`cat $DIR/${TENANT}_${CRED}_credential_unpacked.json | jq '.payload.vp'`
    if [ ! "x$VP" = "xnull" ]
    then
        echo "ERROR: $TENANT - $CRED VCDM2 credential contains a vp claim"
        exit 1
    fi

    ALG=`cat $DIR/${TENANT}_${CRED}_credential_unpacked.json | jq '.header.alg'`
    if [ "x$ALG" = "x" -o "x$ALG" = "xnull" ]
    then
        echo "ERROR: $TENANT - $CRED VCDM2 credential has incorrect alg header ('$ALG')"
        exit 1
    fi
    TYP=`cat $DIR/${TENANT}_${CRED}_credential_unpacked.json | jq -r '.header.typ'`
    if [ ! "x$TYP" = "xvc+jwt" ]
    then
        echo "ERROR: $TENANT - $CRED VCDM2 credential has incorrect typ header ('$TYP')"
        exit 1
    fi
    CTY=`cat $DIR/${TENANT}_${CRED}_credential_unpacked.json | jq -r '.header.cty'`
    if [ ! "x$CTY" = "xvc" -a ! "x$CTY" = "xnull" -a ! "x$CTY" = "x" ]
    then
        echo "ERROR: $TENANT - $CRED VCDM2 credential has incorrect CTY header ('$CTY')"
        exit 1
    fi

    CTX=`cat $DIR/${TENANT}_${CRED}_credential_unpacked.json | jq -r '.payload.["@context"][0]'`
    if [ ! "x$CTX" = "xhttps://www.w3.org/ns/credentials/v2" ]
    then
        echo "ERROR: $TENANT - $CRED VCDM2 credential has incorrect @context attribute ('$CTX')"
        exit 1
    fi
    TYPE2=`cat $DIR/${TENANT}_${CRED}_credential_unpacked.json | jq -r '.payload.type | join(",")'`
    if [ ! "x$TYPE2" = "xVerifiableCredential,$CREDID" ]
    then
        echo "ERROR: $TENANT - $CRED VCDM2 credential has incorrect type attribute ('$TYPE2' vs 'VerifiableCredential,$CREDID')"
        exit 1
    fi

    ISS=`cat $DIR/${TENANT}_${CRED}_credential_unpacked.json | jq -r '.header.iss'`
    if [ "x$ISS" = "x" -o "x$ISS" = "xnull" ]
    then
        ISS=`cat $DIR/${TENANT}_${CRED}_credential_unpacked.json | jq -r '.payload.iss'`
    fi   
    if [ "x$ISS" = "x" -o "x$ISS" = "xnull" ]
    then
        ISS=`cat $DIR/${TENANT}_${CRED}_credential_unpacked.json | jq -r '.payload.issuer.id'`
    fi
    echo "VCDM2 issuer $ISS"
fi

echo "Checking issuer DID"
# we expect one of the following forms 
# - did:web:<issuer-base-url>:<tenant>:.well-known
# - did:web:<tenant>.<issuer-base-url>
# - did:web:<issuer-base-url> (special case for single issuers)
if [ "x$ISS" = "x" -o "x$ISS" = "xnull" ]
then
    echo "ERROR: $TENANT - $CRED Missing issuer"
    exit 1
fi

yarn --cwd ../.. do resolve -k $ISS > $DIR/issuer_key.json

if [ "x$CTYPE" = "xvc1" -o "x$CTYPE" = "xvc2" ]
then
    KID=`cat $DIR/${TENANT}_${CRED}_credential_unpacked.json | jq -r '.header.kid'`
    # our did:web implementation should always return a #0 key reference
    if [ ! "x$KID" = "x$ISS#0" -a ! "x$KID" = "x#0" ]
    then
        echo "ERROR: $TENANT - $CRED Invalid keyid $KID"
        exit 1
    fi

    # for the signature verification, we should actually use KID, but in our
    # implementations the did:web only ever has a single key, referenced with #0
    FILE=`realpath $DIR/${TENANT}_${CRED}_credential.jwt`
    KEYFILE=`realpath $DIR/issuer_key.json`
    STATUS=`yarn --cwd ../.. do jwt:verify -d $FILE -k $KEYFILE | jq '.status'`
    if [ "x$STATUS" = "xnok" -o "x$STATUS" = "x" -o "x$STATUS" = "xnull" ]
    then
        echo "ERROR: $TENANT - $CRED Could not verify signature of issuer"
        exit 1       
    fi
fi

IFS=',' read -ra keys <<< "$KEYS"
for key in ${keys[@]}
do
    # skip accidentally checking the credentialSubject.id
    if [ ! "x$key" = "xid" ]
    then
        echo "Checking claim $key"
        if [ "x$CTYPE" = "xvc2" ]
        then
            CONTENT=`cat $DIR/${TENANT}_${CRED}_credential_unpacked.json | jq ".payload.credentialSubject.[\"$key\"]"`       
        fi

        if [ "x$CONTENT" = "x" -o "x$CONTENT" = "xnull" ]
        then
            echo "ERROR: $TENANT - $CRED Missing claim $key in credential ('$CONTENT')"
            exit 1
        fi

        if [ "$HASFULLCRED" = "0" ]
        then
            DATA=`cat credentials/${CRED}.json | jq ".data.[\"$key\"]"`
        else
            if [ "x$CTYPE" = "xvc2" ]
            then
                DATA=`cat credentials/${CRED}.json | jq ".credential.credentialSubject.[\"$key\"]"`
            fi
        fi

        if [ ! "x$DATA" = "x$CONTENT" ]
        then
            echo "ERROR: $TENANT - $CRED Claim in credential ('$CONTENT') does not match original ('$DATA')"
            exit 1
        fi
    fi
done

if [ "x$CTYPE" = "xvc2" ]
then
    SUBID=`cat $DIR/${TENANT}_${CRED}_credential_unpacked.json | jq '.payload.credentialSubject.id'`
    DIDJWK=`cat $DIR/key.json | jq '.didJWK'`
    if [ ! "x$SUBID" = "x$DIDJWK" ]
    then
        echo "ERROR: $TENANT - $CRED VCDM2 was not bound to the original key"
        exit 1
    fi

    SUBID=`cat $DIR/${TENANT}_${CRED}_credential_unpacked.json | jq '.payload.sub'`
    if [ ! "x$SUBID" = "x" -a ! "x$SUBID" = "xnull" -a ! "x$SUBID" = "x$DIDJWK" ]
    then
        echo "ERROR: $TENANT - $CRED VCDM2 contains a sub claim, but it is not bound to the original key"
        exit 1
    fi
fi


