#!/bin/bash

TENANT=$1
CRED=$2
DIR=$3
SECRET=$4

ISSUERURL=`cat $DIR/openid-credential-issuer.$TENANT.1.json | jq -r '.credential_issuer'`
CREDENTIALENDPOINT=`cat $DIR/openid-credential-issuer.$TENANT.1.json | jq -r '.credential_endpoint'`
NONCEENDPOINT=`cat $DIR/openid-credential-issuer.$TENANT.1.json | jq -r '.nonce_endpoint'`
TOKENENDPOINT=`cat $DIR/oauth-authorization-server.$TENANT.1.json | jq -r '.token_endpoint'`

DATA=`cat credentials/${CRED}.json | jq '.data'`
CREDDATA=`cat credentials/${CRED}.json | jq '.credential'`
TYPE=`cat credentials/${CRED}.json | jq -r '.credential_id'`

if [ "x$DATA" = "x" -o "x$DATA" = "xnull" ]
then
    echo "{
    \"grants\": {
        \"urn:ietf:params:oauth:grant-type:pre-authorized_code\": {
            \"pre-authorized_code\": \"generate\"
        }
    },
    \"credentials\": [\"$TYPE\"],
    \"credential\": $CREDDATA
}" | jq '.' > $DIR/${TENANT}_${CRED}_offer.json
else
    echo "{
    \"grants\": {
        \"urn:ietf:params:oauth:grant-type:pre-authorized_code\": {
            \"pre-authorized_code\": \"generate\"
        }
    },
    \"credentials\": [\"$TYPE\"],
    \"credentialDataSupplierInput\": $DATA
}" | jq '.' > $DIR/${TENANT}_${CRED}_offer.json
fi

FILE=`realpath $DIR/${TENANT}_${CRED}_offer.json`
yarn --cwd ../.. do create:offer -u $ISSUERURL -s "$SECRET" -d $FILE > $DIR/${TENANT}_${CRED}_offer_response.json

URI=`cat $DIR/${TENANT}_${CRED}_offer_response.json | jq -r '.uri'`
if [ "x$URI" = "x" ]
then
    echo "ERROR: $TENANT - $CRED Failed to retrieve offer URI"
    exit 1
fi

echo "Retrieving offer on $TENANT for $CRED"
yarn --cwd ../.. do get:offer -u "$URI" > $DIR/${TENANT}_${CRED}_offer_retrieval.json

ISSURL=`cat $DIR/${TENANT}_${CRED}_offer_retrieval.json | jq -r '.credential_issuer'`
AUTHGRANT=`cat $DIR/${TENANT}_${CRED}_offer_retrieval.json | jq -r '.grants.authorization_code.issuer_state'`
PREAUTHGRANT=`cat $DIR/${TENANT}_${CRED}_offer_retrieval.json | jq -r '.grants.["urn:ietf:params:oauth:grant-type:pre-authorized_code"].["pre-authorized_code"]'`
TXCODE=`cat $DIR/${TENANT}_${CRED}_offer_retrieval.json | jq '.grants.["urn:ietf:params:oauth:grant-type:pre-authorized_code"].tx_code'`
CREDID=`cat $DIR/${TENANT}_${CRED}_offer_retrieval.json | jq -r '.credential_configuration_ids[0]'`

if [ "x$ISSURL" = "x" ]
then
    echo "ERROR: $TENANT - $CRED Invalid credential offer, no credential_issuer URL found"
    exit 1
fi

if [ ! "x$ISSURL" = "x$ISSUERURL" ]
then
    echo "ERROR: $TENANT - $CRED Credential issuer url ('$ISSURL') does not match expected value ('$ISSUERURL')"
    exit 1
fi

if [ "x$AUTHGRANT" = "x" -a "x$PREAUTHGRANT" = "x" ]
then
    echo "ERROR: $TENANT - $CRED Invalid credential offer, supported grant found"
    exit 1
fi

# this is a specific test for our situation: the credentials attribute in our create-offer call actually contains a single
# credential_configuration_id from the metadata
if [ ! "x$CREDID" = "x$TYPE" ]
then 
    echo "ERROR: $TENANT - $CRED Invalid credential offer, credential configuration id ('$CREDID') does not match that of create offer ('$TYPE')"
    exit 1
fi

if [ "x$AUTHGRANT" = "xnull" ]
then
    if [ ! "x$TXCODE" = "xnull" ]
    then
        echo "ERROR: $TENANT - $CRED tx_code not implemented yet"
        exit 1
    fi

    echo "Performing pre-authorisation code flow"
    echo "{
        \"grant_type\": \"urn:ietf:params:oauth:grant-type:pre-authorized_code\",
        \"pre-authorized_code\": \"$PREAUTHGRANT\",
        \"authorization_details\": [{
            \"type\": \"openid_credential\",
            \"credential_configuration_id\": \"$CREDID\"
        }]
    }" > $DIR/${TENANT}_${CRED}_token_request.json 
    FILE=`realpath $DIR/${TENANT}_${CRED}_token_request.json`
    yarn --cwd ../.. do get:token -u "$TOKENENDPOINT" -d $FILE > $DIR/${TENANT}_${CRED}_token.json     
else
    if [ ! "x$TXCODE" = "xnull" ]
    then
        echo "ERROR: $TENANT - $CRED Authorisation code flow contains a tx_code attribute, only supported for pre-authorisation_code flow"
        exit 1
    fi

    echo "ERROR: authorisation_code flow not supported yet"
    exit 1
fi

ACCESSTOKEN=`cat $DIR/${TENANT}_${CRED}_token.json | jq -r '.access_token'`
if [ "x$ACCESSTOKEN" = "x" -o "x$ACCESSTOKEN" = "xnull" ]
then
    echo "ERROR: $TENANT - $CRED Did not get a valid access token"
    exit 1
fi

TTYPE=`cat $DIR/${TENANT}_${CRED}_token.json | jq -r '.token_type'`
if [ "x$TTYPE" != "xbearer" ]
then
    echo "ERROR: $TENANT - $CRED Access token type is not bearer, not supported"
    exit 1
fi

NONCE=`cat $DIR/${TENANT}_${CRED}_token.json | jq -r '.c_nonce'`
if [ ! "x$NONCE" = "xnull" ]
then
    echo "WARNING: $TENANT - $CRED publishes old-style c_nonce attribute"
fi

AUTHDETAILSTYPE=`cat $DIR/${TENANT}_${CRED}_token.json | jq -r '.authorization_details[0].type'`
if [ ! "x$AUTHDETAILSTYPE" = "xopenid_credential" ]
then
    echo "ERROR: $TENANT - $CRED authorization details type incorrect, or multiple entries found"
    exit 1
fi

CREDSETID=`cat $DIR/${TENANT}_${CRED}_token.json | jq -r '.authorization_details[0].credential_identifiers[0]'`

echo "Retrieving a fresh nonce value"
yarn --cwd ../.. do get:json -u $NONCEENDPOINT -m POST > $DIR/${TENANT}_${CRED}_nonce.json
NONCE=`cat $DIR/${TENANT}_${CRED}_nonce.json | jq -r '.c_nonce'`
if [ "x$NONCE" = "xnull" ]
then
    echo "ERROR: $TENANT - $CRED could not retrieve a fresh nonce value"
fi

echo "Creating proof"
KFILE=`realpath $DIR/key.json`
yarn --cwd ../.. do create:proof -k $KFILE -n $NONCE -u $ISSUERURL > $DIR/${TENANT}_${CRED}_proof.json
PROOF=`cat $DIR/${TENANT}_${CRED}_proof.json | jq '.proof'`

if [ "x$PROOF" = "x" -o "x$PROOF" = "xnull" -o "x$PROOF" = "x\"null\"" ]
then
    echo "ERROR: $TENANT - $CRED Could not create proof for credential request"
    exit 1
fi

echo "Retrieving the credential"
echo "{
    \"credential_identifier\": \"$CREDSETID\",
    \"proofs\": {
        \"jwt\": [$PROOF]
    }
}" > $DIR/${TENANT}_${CRED}_credential_request.json
FILE=`realpath $DIR/${TENANT}_${CRED}_credential_request.json`

yarn --cwd ../.. do get:credential -u $CREDENTIALENDPOINT -s $ACCESSTOKEN -d $FILE > $DIR/${TENANT}_${CRED}_credential.json
CREDENTIAL=`cat $DIR/${TENANT}_${CRED}_credential.json | jq -r '.credentials[0].credential'`

if [ "x$CREDENTIAL" = "x" -o "x$CREDENTIAL" = "xnull" ]
then
    echo "ERROR: $TENANT - $CRED No credential received"
    exit 1
fi

